import sys
import sqlite3
import os
con = sqlite3.connect('Assets\Plugins\juego.db')
cursorObj = con.cursor()


cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (18,'Ana Lucia',10,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (19,'Ana Lucia',17,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (20,'Ana Lucia',2,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (21,'Annelesse Mayara',2,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (22,'Annelesse Mayara',10,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (23,'Annelesse Mayara',20,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (24,'Annelesse Mayara',5,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (25,'Karla Faviana',20,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (26,'Karla Faviana',18,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (27,'Karla Faviana',19,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (28,'Karla Faviana',15,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (29,'Rosario Graciela',12,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (30,'Rosario Graciela',15,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (31,'Rosario Graciela',18,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (32,'Rosario Graciela',11,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (33,'Anahi Lucero Llacho Oviedo',20,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (34,'Anahi Lucero Llacho Oviedo',5,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (35,'Anahi Lucero Llacho Oviedo',2,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (36,'Anahi Lucero Llacho Oviedo',20,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (37,'Aracely Talia Perez Ramos',20,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (38,'Aracely Talia Perez Ramos',10,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (39,'Aracely Talia Perez Ramos',15,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (40,'Aracely Talia Perez Ramos',5,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (41,'Keily Brunela Berlanga Cornejo',10,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (42,'Keily Brunela Berlanga Cornejo',0,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (43,'Keily Brunela Berlanga Cornejo',5,05-12-2019,15);")
cursorObj.execute("Insert into Registro (idreg,Nickalumno,Notaal,Fecha,Score) values (44,'Keily Brunela Berlanga Cornejo',15,05-12-2019,15);")

cursorObj.execute('SELECT usuario.nickname,registro.notaal FROM registro inner join usuario on usuario.nickname=registro.Nickalumno')
con.commit()
rows = cursorObj.fetchall()
for i in rows:
    print(i)
